name: Generate Design Tokens With Style Dictionary
on:
  workflow_dispatch:
    # inputs:
    #   file_key:
    #     description: 'The file key of the Figma file to be updated'
    #     required: true


jobs:
  generate_tokens:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node Dependencies
      run: npm install style-dictionary
    # - name: Install Token Studio extension (not used, but brings in style-dictionary anyway)
    #   run: npm install @tokens-studio/sd-transforms
    - name: Build Style Dictionary
      run: npm run build
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Token Conversaion
        title: Token Conversaion
        body: 'Token Conversaion'
        branch: update-tokens

    
