name: Generate Design Tokens With Style Dictionary
on:
  workflow_dispatch:
    inputs:
      file_key:
        description: 'The file key of the Figma file to be updated'
        required: true


jobs:
  generate_tokens:
    # if: ${{ github.event.label.name == 'Design tokens' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node Dependencies
      run: npm install style-dictionary
    - name: Build Style Dictionary
      run: npm run build
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        commit-message: Update tokens from Figma
        title: Update tokens from Figma
        body: 'Update tokens from Figma from file: https://www.figma.com/file/${{ github.event.inputs.file_key }}'
        branch: update-tokens

    
